name: derry
description: Derry is a script manager for Dart. It helps you define script shortcuts and use them effortlessly, and performantly as it should be.
version: 0.1.1
homepage: https://github.com/frencojobs/derry

environment:
  sdk: ">=2.8.1 <3.0.0"

executables:
  derry:

dependencies:
  ffi: ^1.0.0
  args: ^2.1.0
  yaml: ^3.1.0
  console: ^4.1.0
  equatable: ^2.0.0
  string_similarity: ^2.0.0

dev_dependencies:
  test: ^1.17.0
  pedantic: ^1.11.0
  build_runner: ^2.0.1
  build_version: ^2.0.3

scripts: derry.yaml
